
spring:
    application:
        name: "@project.name@"
        version: "@project.version@"
        majorVersion: ${APP_VERSION:1}
    datasource:
        url: jdbc:h2:mem:interviewdb
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    flyway:
        enabled: true
        locations: classpath:db/migrations/
        baseline-on-migrate: true
    h2:
        console:
            enabled: true